name: app_buy_sell
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  go_router: ^13.1.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  riverpod_generator: ^2.3.9
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_gen:
  integrations:
    flutter_svg: true
